In [33]:
import pandas as pd

In [34]:
data=pd.read_csv('bmi_data.csv')

In [35]:
data.head()

Sex  Age  Height(Inches)  Weight(Pounds)        BMI
0  Female   21        65.78331        112.9925  18.357646
1  Female   35        71.51521        136.4873  18.762652
2  Female   27        69.39874        153.0269  22.338985
3    Male   24        68.21660        142.3354  21.504612
4  Female   18        67.78781        144.2971  22.077669

In [36]:
data.isnull().sum()

Sex                0
Age                0
Height(Inches)    19
Weight(Pounds)    16
BMI               50
dtype: int64

In [37]:
data = data[(data != 0).all(axis=1)]

In [38]:
condition = (data[['Height(Inches)','Weight(Pounds)']] == 0).any(axis=1)

# Menghapus baris yang memenuhi kondisi
data = data.drop(data[condition].index)
print("\nDataFrame setelah penghapusan:")
print(data)


DataFrame setelah penghapusan:
          Sex  Age  Height(Inches)  Weight(Pounds)        BMI
0      Female   21        65.78331        112.9925  18.357646
1      Female   35        71.51521        136.4873  18.762652
2      Female   27        69.39874        153.0269  22.338985
3        Male   24        68.21660        142.3354  21.504612
4      Female   18        67.78781        144.2971  22.077669
...       ...  ...             ...             ...        ...
24995    Male   35        69.50215        118.0312  17.179051
24996    Male   26        64.54826        120.1932  20.281947
24997  Female   23        64.69855        118.2655  19.864050
24998    Male   20        67.52918        132.2682  20.392540
24999  Female   34        68.87761        124.8742  18.506121

[25000 rows x 5 columns]


In [39]:
data['Sex'] = data['Sex'].map({'Male': 1, 'Female': 0})

In [40]:
data.head()

Sex  Age  Height(Inches)  Weight(Pounds)        BMI
0    0   21        65.78331        112.9925  18.357646
1    0   35        71.51521        136.4873  18.762652
2    0   27        69.39874        153.0269  22.338985
3    1   24        68.21660        142.3354  21.504612
4    0   18        67.78781        144.2971  22.077669

In [41]:
#mengubah data height dan weight untukbmr
data['Height(CM)'] = data['Height(Inches)'] * 2.54
data['Weight(KG)'] = data['Weight(Pounds)'] * 0.453592

In [42]:
data.head()

Sex  Age  Height(Inches)  Weight(Pounds)        BMI  Height(CM)  Weight(KG)
0    0   21        65.78331        112.9925  18.357646  167.089607   51.252494
1    0   35        71.51521        136.4873  18.762652  181.648633   61.909547
2    0   27        69.39874        153.0269  22.338985  176.272800   69.411778
3    1   24        68.21660        142.3354  21.504612  173.270164   64.562199
4    0   18        67.78781        144.2971  22.077669  172.181037   65.452010

In [43]:
columns_to_drop = ['BMI', 'Height(Inches)', 'Weight(Pounds)']
data = data.drop(columns=columns_to_drop)

In [44]:
data.head()

Sex  Age  Height(CM)  Weight(KG)
0    0   21  167.089607   51.252494
1    0   35  181.648633   61.909547
2    0   27  176.272800   69.411778
3    1   24  173.270164   64.562199
4    0   18  172.181037   65.452010

In [45]:
columns_to_check = ['Height(CM)', 'Weight(KG)']
data = data.dropna(subset=columns_to_check, how='any')

In [46]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24967 entries, 0 to 24999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Sex         24967 non-null  int64  
 1   Age         24967 non-null  int64  
 2   Height(CM)  24967 non-null  float64
 3   Weight(KG)  24967 non-null  float64
dtypes: float64(2), int64(2)
memory usage: 975.3 KB


In [47]:
# fungsi untuk menghitung bmr
def calculate_bmr(row):
    if row['Sex'] == 1:
        return 66 + (13.7 * row['Weight(KG)']) + (5 * row['Height(CM)']) - (6.8 * row['Age'])
    elif row['Sex'] == 0:
        return 665 + (9.6 * row['Weight(KG)']) + (1.8 * row['Height(CM)']) - (4.7 * row['Age'])
    else:
        return None 

In [48]:
data['BMR'] = data.apply(calculate_bmr, axis=1)

In [49]:
data.head()

Sex  Age  Height(CM)  Weight(KG)          BMR
0    0   21  167.089607   51.252494  1359.085236
1    0   35  181.648633   61.909547  1421.799195
2    0   27  176.272800   69.411778  1521.744104
3    1   24  173.270164   64.562199  1653.652943
4    0   18  172.181037   65.452010  1518.665165

In [50]:
data.describe()

Sex           Age    Height(CM)    Weight(KG)           BMR
count  24967.000000  24967.000000  24967.000000  24967.000000  24967.000000
mean       0.503585     26.498738    172.701406     57.641677   1472.471234
std        0.499997      5.190868      4.830149      5.289591    104.668750
min        0.000000     18.000000    153.107034     35.386871   1119.665286
25%        0.000000     22.000000    169.429849     54.117268   1394.997285
50%        1.000000     27.000000    172.708519     57.675765   1457.148242
75%        1.000000     31.000000    175.950309     61.186476   1543.496065
max        1.000000     35.000000    190.888112     77.529759   1859.400783

In [51]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24967 entries, 0 to 24999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Sex         24967 non-null  int64  
 1   Age         24967 non-null  int64  
 2   Height(CM)  24967 non-null  float64
 3   Weight(KG)  24967 non-null  float64
 4   BMR         24967 non-null  float64
dtypes: float64(3), int64(2)
memory usage: 1.1 MB


In [56]:
# Mengatur ulang batas bin untuk 3 kategori
bins = [data['BMR'].min(), data['BMR'].quantile(0.33), data['BMR'].quantile(0.66), data['BMR'].max()]
labels = ['Rendah', 'Sedang', 'Tinggi']

# Menambahkan kolom baru dengan kategori berdasarkan nilai BMR
data['BMR_Category'] = pd.cut(data['BMR'], bins=bins, labels=labels)


In [57]:
from sklearn.preprocessing import LabelEncoder

# Inisialisasi LabelEncoder
label_encoder = LabelEncoder()

# Melakukan encoding pada kolom BMR_Category
data['BMR_Category_Encoded'] = label_encoder.fit_transform(data['BMR_Category'])

In [58]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24967 entries, 0 to 24999
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype   
---  ------                --------------  -----   
 0   Sex                   24967 non-null  int64   
 1   Age                   24967 non-null  int64   
 2   Height(CM)            24967 non-null  float64 
 3   Weight(KG)            24967 non-null  float64 
 4   BMR                   24967 non-null  float64 
 5   BMR_Category          24966 non-null  category
 6   BMR_Category_Encoded  24967 non-null  int32   
dtypes: category(1), float64(3), int32(1), int64(2)
memory usage: 1.3 MB


In [59]:
data.head()

Sex  Age  Height(CM)  Weight(KG)          BMR BMR_Category  \
0    0   21  167.089607   51.252494  1359.085236       Rendah   
1    0   35  181.648633   61.909547  1421.799195       Sedang   
2    0   27  176.272800   69.411778  1521.744104       Tinggi   
3    1   24  173.270164   64.562199  1653.652943       Tinggi   
4    0   18  172.181037   65.452010  1518.665165       Tinggi   

   BMR_Category_Encoded  
0                     0  
1                     1  
2                     2  
3                     2  
4                     2

In [61]:
data.BMR_Category_Encoded.unique()

array([0, 1, 2, 3])

In [63]:
data = data.drop(index=22945)

In [64]:
data.BMR_Category_Encoded.unique()

array([0, 1, 2])

### membuat model untuk data


In [65]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [66]:
X = data.drop(columns=['BMR','BMR_Category_Encoded','BMR_Category'])

In [67]:
Y = data['BMR_Category_Encoded']
print(Y)

0        0
1        1
2        2
3        2
4        2
        ..
24995    1
24996    1
24997    0
24998    2
24999    0
Name: BMR_Category_Encoded, Length: 24966, dtype: int32


In [68]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [69]:
from sklearn.preprocessing import StandardScaler
# Normalisasi fitur
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [70]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, input_dim=X_train.shape[1], activation='relu'),
    tf.keras.layers.Dense(32,activation='relu'),
    tf.keras.layers.Dense(5,activation='softmax')
])
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# Melatih model
model.fit(X_train, Y_train, epochs=20, batch_size=32, validation_data=(X_test, Y_test))

_, accuracy = model.evaluate(X_test, Y_test)
print(f'Akurasi model: {accuracy}')

Epoch 1/20
625/625 [==============================] - 4s 5ms/step - loss: 0.2701 - accuracy: 0.9311 - val_loss: 0.0680 - val_accuracy: 0.9856
Epoch 2/20
625/625 [==============================] - 2s 3ms/step - loss: 0.0520 - accuracy: 0.9868 - val_loss: 0.0463 - val_accuracy: 0.9816
Epoch 3/20
625/625 [==============================] - 3s 4ms/step - loss: 0.0382 - accuracy: 0.9889 - val_loss: 0.0324 - val_accuracy: 0.9916
Epoch 4/20
625/625 [==============================] - 3s 4ms/step - loss: 0.0302 - accuracy: 0.9911 - val_loss: 0.0334 - val_accuracy: 0.9876
Epoch 5/20
625/625 [==============================] - 3s 4ms/step - loss: 0.0274 - accuracy: 0.9909 - val_loss: 0.0243 - val_accuracy: 0.9932
Epoch 6/20
625/625 [==============================] - 3s 5ms/step - loss: 0.0234 - accuracy: 0.9923 - val_loss: 0.0263 - val_accuracy: 0.9910
Epoch 7/20
625/625 [==============================] - 3s 5ms/step - loss: 0.0225 - accuracy: 0.9922 - val_loss: 0.0198 - val_accuracy: 0.9942
Epoch 

In [73]:
# Data baru untuk prediksi (ganti nilainya sesuai dengan data yang ingin diprediksi)
new_data = {
    'Sex': 1,
    'Age': 30,
    'Height(CM)': 170,
    'Weight(KG)': 60,
    # Jika kolom 'BMR' tidak ada, ganti nilainya sesuai dengan data aktual
}

# Mengubah data input menjadi bentuk yang dapat diproses oleh model
new_data_df = pd.DataFrame([new_data])  # Ubah data menjadi DataFrame jika belum
new_data_processed = scaler.transform(new_data_df)  # Normalisasi fitur seperti yang dilakukan pada data latih

# Melakukan prediksi dengan model yang sudah dilatih
prediction = model.predict(new_data_processed)
print(f'Prediksi kategori BMR: {prediction}')


1/1 [==============================] - 0s 41ms/step
Prediksi kategori BMR: [[1.10435644e-29 1.96595545e-10 1.00000000e+00 3.37590639e-14
  1.73819292e-13]]


In [74]:
predicted_category = np.argmax(prediction)
print(f'Kategori BMR diprediksi: {predicted_category}')

Kategori BMR diprediksi: 2


In [75]:
data.BMR_Category_Encoded.unique()

array([0, 1, 2])

In [ ]:
data.to_csv('bmi_clean',index=False)

In [76]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24966 entries, 0 to 24999
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype   
---  ------                --------------  -----   
 0   Sex                   24966 non-null  int64   
 1   Age                   24966 non-null  int64   
 2   Height(CM)            24966 non-null  float64 
 3   Weight(KG)            24966 non-null  float64 
 4   BMR                   24966 non-null  float64 
 5   BMR_Category          24966 non-null  category
 6   BMR_Category_Encoded  24966 non-null  int32   
dtypes: category(1), float64(3), int32(1), int64(2)
memory usage: 1.3 MB


In [77]:
data.describe()

Sex           Age    Height(CM)    Weight(KG)           BMR  \
count  24966.000000  24966.000000  24966.000000  24966.000000  24966.000000   
mean       0.503565     26.498518    172.702023     57.642568   1472.485366   
std        0.499997      5.190855      4.829261      5.287821    104.647026   
min        0.000000     18.000000    153.107034     35.637748   1173.203199   
25%        0.000000     22.000000    169.430484     54.117438   1395.001172   
50%        1.000000     27.000000    172.709078     57.676332   1457.163759   
75%        1.000000     31.000000    175.950429     61.186635   1543.498024   
max        1.000000     35.000000    190.888112     77.529759   1859.400783   

       BMR_Category_Encoded  
count          24966.000000  
mean               1.010054  
std                0.818485  
min                0.000000  
25%                0.000000  
50%                1.000000  
75%                2.000000  
max                2.000000